'use strict';

module.exports = [
  {
    key: 'SUPRA_SETUP',
    equipmentGroupCode: 'SUPRA_N',
    checklistKind: 'SETUP',
    getPath: '/supra-setup',
    postPath: '/supra-setup',
  },
  {
    key: 'SUPRA_MAINT',
    equipmentGroupCode: 'SUPRA_N',
    checklistKind: 'MAINT',
    getPath: '/supra-maintenance',
    postPath: '/supra-maintenance/request-approval',
    responseStatus: 'SUBMITTED',
    bodyPath: 'checklistData',
  },
  {
    key: 'SUPRAXP_SETUP',
    equipmentGroupCode: 'SUPRA_XP',
    checklistKind: 'SETUP',
    getPath: '/supraxp-setup',
    postPath: '/supraxp-setup',
  },
  {
    key: 'SUPRAXP_MAINT',
    equipmentGroupCode: 'SUPRA_XP',
    checklistKind: 'MAINT',
    getPath: '/supraxp-maintenance',
    postPath: '/supraxp-maintenance',
  },
  {
    key: 'INTEGER_SETUP',
    equipmentGroupCode: 'INTEGER',
    checklistKind: 'SETUP',
    getPath: '/integer-setup',
    postPath: '/integer-setup',
  },
  {
    key: 'INTEGER_MAINT',
    equipmentGroupCode: 'INTEGER',
    checklistKind: 'MAINT',
    getPath: '/integer-maintenance',
    postPath: '/integer-maintenance',
  },
  {
    key: 'PRECIA_SETUP',
    equipmentGroupCode: 'PRECIA',
    checklistKind: 'SETUP',
    getPath: '/precia-setup',
    postPath: '/precia-setup',
  },
  {
    key: 'PRECIA_MAINT',
    equipmentGroupCode: 'PRECIA',
    checklistKind: 'MAINT',
    getPath: '/precia-maintenance',
    postPath: '/precia-maintenance',
  },
  {
    key: 'ECOLITE_SETUP',
    equipmentGroupCode: 'ECOLITE_300',
    checklistKind: 'SETUP',
    getPath: '/ecolite-setup',
    postPath: '/ecolite-setup',
  },
  {
    key: 'ECOLITE_MAINT',
    equipmentGroupCode: 'ECOLITE_300',
    checklistKind: 'MAINT',
    getPath: '/ecolite-maintenance',
    postPath: '/ecolite-maintenance',
  },
  {
    key: 'GENEVA_SETUP',
    equipmentGroupCode: 'GENEVA',
    checklistKind: 'SETUP',
    getPath: '/geneva-setup',
    postPath: '/geneva-setup',
  },
  {
    key: 'GENEVA_MAINT',
    equipmentGroupCode: 'GENEVA',
    checklistKind: 'MAINT',
    getPath: '/geneva-maintenance',
    postPath: '/geneva-maintenance',
  },
  {
    key: 'HDW_SETUP',
    equipmentGroupCode: 'HDW',
    checklistKind: 'SETUP',
    getPath: '/hdw-setup',
    postPath: '/hdw-setup',
  },
  {
    key: 'HDW_MAINT',
    equipmentGroupCode: 'HDW',
    checklistKind: 'MAINT',
    getPath: '/hdw-maintenance',
    postPath: '/hdw-maintenance',
  },
];
